# Runs on master branch of our github repo
trigger:
- master

# Define variables
variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: Build
    displayName: Build Job
    pool:
      vmImage: 'ubuntu-latest'
    steps:

# Build docker image and push to ACR
    - task: Docker@2
      inputs:
        containerRegistry: 'manual-devops-sc'
        repository: 'python-restapi1'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags:
          $(tag)

# Copy files from a source folder to target folder
    #- bash: echo Contents in System Default Working Directory; ls -R $(System.DefaultWorkingDirectory)
    #- bash: echo Before copying Contents in Build Artifact Directory; ls -R $(Build.ArtifactStagingDirectory)
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        Overwrite: true

# Publish Artifacts to Azure Pipelines
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: python-restapi1
        publishLocation: 'Container'